/*
 * This source file was generated by the Gradle 'init' task
 */
package rs.vexide;

public class Robot {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Robot app = new Robot();
        String greeting = app.getGreeting();
        vexPrintln(greeting);
    }

    private static native void vexPrintln(String value);
}
